IHub-175771 Update "ihub_sample" to showcase new approaches for creating an integration
ov-integrations/ihub_sample pull request #4
Opened 2022-02-10 05:03 UTC by glebowadim

2022-02-15 07:32 UTC, asmoiseenko requested changes

2022-02-15 07:32 UTC, asmoiseenko commented on settings.json
> +"URL":"https://"
Rename to OneVizionURL

2022-02-15 07:32 UTC, asmoiseenko commented on settings.json
>  "UserName":"",
Rename to OneVizionUser

2022-02-15 07:32 UTC, asmoiseenko commented on settings.json
>  "Password":"",
rename to OneVizionSecurityToken

2022-02-16 07:48 UTC, Anastasiyaaa requested changes

2022-02-16 07:48 UTC, Anastasiyaaa commented on README.md
> +- jsonschema library
Maybe add links?

2022-02-16 07:48 UTC, Anastasiyaaa commented on README.md
>  The integration adds logs of the different log levels (Info, Warning, Error, Debug) every 5 seconds.
I suggest adding a mention of the "Log Level" DropDown that iHub has (because logging is all that integration does)

2022-02-17 03:12 UTC, glebowadim commented on README.md
>  ## Usage
Removed

2022-02-17 03:13 UTC, glebowadim commented on README.md
> +Sample Integration adds integration logs via API and writes messages to stdout.
Added

2022-02-17 03:13 UTC, glebowadim commented on SampleIntegration.py
>  import time
Done

2022-02-17 03:14 UTC, glebowadim commented on SampleIntegration.py
> +    ov_integration.add_log()
Moved to sample.py

2022-02-17 03:23 UTC, glebowadim commented on SmallSampleIntegration.py
> +for i in range(3):
I split all code into sample.py and start.py

2022-02-17 03:23 UTC, glebowadim commented on settings.json
> +"URL":"https://"
Ranamed

2022-02-17 03:23 UTC, glebowadim commented on settings.json
>  "UserName":"",
Ranamed

2022-02-17 03:25 UTC, glebowadim commented on settings.json
>  "Password":"",
Renamed

Do you mean only renaming or should I use token authentication?

2022-02-17 03:27 UTC, glebowadim commented on README.md
> +- jsonschema library
Now this block is meaningless
Removed

2022-02-17 03:46 UTC, glebowadim commented on README.md
>  The integration adds logs of the different log levels (Info, Warning, Error, Debug) every 5 seconds.
I don't think it's needed here. I think we can add this to the wiki

2022-02-17 04:38 UTC, asmoiseenko requested changes

2022-02-17 04:38 UTC, asmoiseenko commented on README.md
> +**sample.py** contains a main business logic. **start.py** is an executable python script.
... executable python script, which acts as a wrapper to read/validate configuration, install dependencies, and launche **sample.py**.

2022-02-17 04:38 UTC, asmoiseenko commented on sample.py
> +        url = url.replace("https://", "").replace("http://", "")
I think it is bad idea to strip protocol part from the url parameter, propose to move this logic to the call of `IntegrationLog` constructor:
```
        self.integration_log_service = IntegrationLog(processId=process_id,
                                                      URL=url.replace("https://", "").replace("http://", ""),
                                                      userName=user_name,
                                                      password=password,
                                                      logLevelName=log_level_name)
```

2022-02-17 04:38 UTC, asmoiseenko commented on sample.py
> +    def _add_logs(self):
I do not see any value of this routine, move single statement creating INFO level log entry to the start`s method loop

2022-02-17 04:38 UTC, asmoiseenko commented on sample.py
> +            print(i, flush=True)
why do you call `print` here?

2022-02-17 04:38 UTC, asmoiseenko commented on sample.py
> +        self.integration_log_service = IntegrationLog(processId=process_id,
Since log initialization is a common task for each integration, maybe it makes sense to move it to the `start.py`?

2022-02-17 09:13 UTC, asmoiseenko commented on settings.json
>  "Password":"",
Use token - this is best preactise

2022-02-20 09:04 UTC, glebowadim commented on README.md
> +**sample.py** contains a main business logic. **start.py** is an executable python script.
Done

2022-02-20 09:04 UTC, glebowadim commented on sample.py
> +        url = url.replace("https://", "").replace("http://", "")
Done

2022-02-20 09:04 UTC, glebowadim commented on sample.py
> +    def _add_logs(self):
Done

2022-02-20 09:06 UTC, glebowadim commented on sample.py
> +        self.integration_log_service = IntegrationLog(processId=process_id,
Done

2022-02-20 09:06 UTC, glebowadim commented on settings.json
>  "Password":"",
Done

2022-02-20 09:11 UTC, glebowadim commented on sample.py
> +            print(i, flush=True)
It was added to demonstrate "Read from stdout" feature. How to write log from stdout.
Not sure if this is needed here now.

2022-02-20 09:14 UTC, glebowadim commented
@asmoiseenko 
Can you also mark the security hotspot as false positive?

2022-02-21 02:52 UTC, asmoiseenko requested changes

2022-02-21 02:52 UTC, asmoiseenko commented on start.py
> +access_key = settings_file_json["OneVizionAccessKey"]
Let's add some comments to highlight the purpose of each code block:
#read, validate, and parse integration settings file
#read standard integration environment properties
#initialize logging
#start the main integration code

Add comments to the `log_level`, ie:
```python
log_level = ihub_data['logLevel'] #retrieved from the integration`s settings in OneVizion
```

and `process_id`
```python
process_id = ihub_data['processId'] #the process_id of the current integration run in OneVizion
```

2022-02-21 02:52 UTC, asmoiseenko commented on sample.py
> +            print(i, flush=True)
Let's remove

2022-02-21 05:03 UTC, glebowadim commented on sample.py
> +            print(i, flush=True)
Done

2022-02-21 05:04 UTC, glebowadim commented on start.py
> +access_key = settings_file_json["OneVizionAccessKey"]
Done

2022-02-21 06:58 UTC, asmoiseenko approved these changes

2022-02-21 08:00 UTC, Anastasiyaaa approved these changes

2022-02-21 08:14 UTC, P4radise approved these changes

2022-02-21 09:11 UTC, merged